-- =========================================================
-- Customer Analysis
--
-- Purpose:
-- Analyze customer purchasing behavior including:
-- - revenue per customer
-- - order frequency
-- - repeat customer rate
--
-- Grain:
-- 1 row = 1 customer (customer_unique_id)
-- =========================================================


-- ---------------------------------------------------------
-- Query 1: Customer-level revenue and order metrics
-- ---------------------------------------------------------

SELECT
    c.customer_unique_id,

    -- Number of orders per customer
    COUNT(DISTINCT oi.order_id) AS orders_cnt,

    -- Total revenue generated by customer
    SUM(oi.price)::numeric AS total_revenue

FROM olist.olist_orders_dataset o

JOIN olist.olist_customers_dataset c
    USING (customer_id)

JOIN olist.olist_order_items_dataset oi
    USING (order_id)

WHERE o.order_status = 'delivered'

GROUP BY c.customer_unique_id

ORDER BY total_revenue DESC;



-- ---------------------------------------------------------
-- Query 2: Customer segmentation
--
-- Segments customers into:
-- - one_time
-- - repeat
--
-- Calculates:
-- - number of customers
-- - average revenue per customer
-- - average orders per customer
-- ---------------------------------------------------------

WITH customer_orders AS (
    SELECT
        c.customer_unique_id,
        COUNT(DISTINCT oi.order_id) AS orders_cnt,
        SUM(oi.price)::numeric AS total_revenue

    FROM olist.olist_orders_dataset o

    JOIN olist.olist_customers_dataset c
        USING (customer_id)

    JOIN olist.olist_order_items_dataset oi
        USING (order_id)

    WHERE o.order_status = 'delivered'

    GROUP BY c.customer_unique_id
),

customer_bucket AS (
    SELECT
        customer_unique_id,
        orders_cnt,
        total_revenue,

        -- Customer segmentation
        CASE
            WHEN orders_cnt = 1 THEN 'one_time'
            ELSE 'repeat'
        END AS customer_type

    FROM customer_orders
)

SELECT
    customer_type,

    -- Number of customers in each segment
    COUNT(customer_unique_id) AS customers_cnt,

    -- Average revenue per customer
    ROUND(AVG(total_revenue), 2) AS avg_revenue_per_customer,

    -- Average number of orders per customer
    ROUND(AVG(orders_cnt), 2) AS avg_orders_per_customer

FROM customer_bucket

GROUP BY customer_type

ORDER BY customer_type;



-- ---------------------------------------------------------
-- Query 3: Repeat customer rate
--
-- Calculates:
-- - total customers
-- - repeat customers
-- - repeat customer rate
-- ---------------------------------------------------------

WITH customer_orders AS (
    SELECT
        c.customer_unique_id,
        COUNT(DISTINCT oi.order_id) AS orders_cnt,
        SUM(oi.price)::numeric AS total_revenue

    FROM olist.olist_orders_dataset o

    JOIN olist.olist_customers_dataset c
        USING (customer_id)

    JOIN olist.olist_order_items_dataset oi
        USING (order_id)

    WHERE o.order_status = 'delivered'

    GROUP BY c.customer_unique_id
),

customer_bucket AS (
    SELECT
        customer_unique_id,
        orders_cnt,

        CASE
            WHEN orders_cnt = 1 THEN 'one_time'
            ELSE 'repeat'
        END AS customer_type

    FROM customer_orders
)

SELECT
    COUNT(customer_unique_id) AS total_customers,

    SUM(CASE
        WHEN customer_type = 'repeat'
        THEN 1
        ELSE 0
    END)::numeric AS repeat_customers,

    ROUND(
        SUM(CASE
            WHEN customer_type = 'repeat'
            THEN 1
            ELSE 0
        END)::numeric
        /
        COUNT(customer_unique_id),
        4
    ) AS repeat_customer_rate

FROM customer_bucket;
